#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Usage: `basename $0` <package_name>"
    exit 1
fi

cd /home/darshan/aur &&
    git clone "https://aur.archlinux.org/$1.git" &&
    cd $1 &&
    makepkg -si
