#!/bin/bash

#chromium --disable-plugins --enable-udd-profiles --user-data-dir=/home/darshan/.config/chromium-fb
#chromium --enable-udd-profiles --user-data-dir=/home/darshan/.config/chromium-fb

google-chrome --enable-udd-profiles --user-data-dir=/home/darshan/.config/chromium-fb
