#!/bin/bash

cd /home/darshan/1010-backup
latest="$(ls -r *.tgz| head -1)"

tar xzf "$latest"
d=${latest%.tgz}
cd "$d"

adb root >/dev/null || { echo "Can't adb root -- is device connected?"; exit 1; }

#adb push 15 /data/data/com.gramgames.tenten/shared_prefs/com.gramgames.tenten_preferences.xml
#adb push 16 /data/data/com.gramgames.tenten/shared_prefs/com.gramgames.tenten.v2.playerprefs.xml
##adb push 19 /data/user/0/com.google.android.gms/files/backup_chunk_listings/com.gramgames.tenten
#adb push 21 /data/user/0/com.gramgames.tenten/shared_prefs/com.gramgames.tenten_preferences.xml
#adb push 22 /data/user/0/com.gramgames.tenten/shared_prefs/com.gramgames.tenten.v2.playerprefs.xml

adb push com.gramgames.tenten_preferences.xml /data/data/com.gramgames.tenten/shared_prefs/
adb push com.gramgames.tenten.v2.playerprefs.xml /data/data/com.gramgames.tenten/shared_prefs/
#adb push com.gramgames.tenten_preferences.xml /data/user/0/com.gramgames.tenten/shared_prefs/
#adb push com.gramgames.tenten.v2.playerprefs.xml /data/user/0/com.gramgames.tenten/shared_prefs/

# I wonder if they symlinks (or hard links!) to each other? (Or mirrored fs or anything...)
#  Might try just doing the first two...

cd ..

rm "$d" -rf


# 136703 without backup_chunk_listings
# 135811
# Crud, so it isn't working... I play, swipe from task manager, reopen... an I'm not where I left off.
# Shoot.
# Let's quit for now.  I do think we're very much on the right track.
# This could perhaps, at least partly, be because we're based on an old backup.
# Starting from scatch at 0 may allow this to work, which would be okay.


# 683
