#!/bin/bash

int_handler()
{
    echo "Interrupted."
    kill $PPID
    exit 1
}
trap 'int_handler' INT


RETRIES=16

if [ $# -ne 1 ]; then
    echo "Usage: `basename $0` <url-or-id>"
    exit 1
fi

n=0
success=false
while [ "$n" -lt "$RETRIES" ]; do
    let "n+=1"

    #echo -e "\e[36m→ ↪→ Try #$n\e[0m"
    #echo -e "\e[36m↪ Try #$n\e[0m"
    #
    echo -e "\e[36m──────────────────────────── Try #$n ────────────────────────────\e[0m"

    youtube-dl -- $1
    if [ "$?" -eq 0 ]; then
        success=true
        break
    fi
done

if [ "$success" = false ]; then
    echo -e "\e[91m✘ Still failed after $RETRIES retries; quitting ✘\e[0m"
else
    retries="retries"
    if [ "$n" -eq 1 ]; then
        retries="retry"
    fi

    echo -e "\e[92m✔ Success!  ($n $retries).\e[0m"
fi
