#!/bin/bash

RETRIES=8

if [ $# -ne 1 ]; then
    echo "Usage: `basename $0` <url-or-id>"
    exit 1
fi

# n=$RETRIES
# until youtube-dl $1; do
#     echo "n = $n"
#     if [ "$n" -eq 0 ]; then
#         echo "Still failed after $RETRIES retries; quitting"
#         break
#     fi

#     let "n-=1"
# done

n=0
success=false
while [ "$n" -lt "$RETRIES" ]; do
    let "n+=1"

    echo "Try #$n"

    youtube-dl $1
    if [ "$?" -eq 0 ]; then
        success=true
        break
    fi
done

if [ "$success" = false ]; then
    echo "Still failed after $RETRIES retries; quitting"
fi
