#!/bin/bash

start=`date +%s%N`

set_tdiff()
{
    local end=`date +%s%N`
    local msdiff=$(( (end - start) / 1000000 ))
    local secs=$(( msdiff / 1000 ))
    local mils=$(( msdiff % 1000 ))
    tdiff="$secs.$mils"
}

int_handler()
{
    set_tdiff

    echo -e "\e[93m▶ Interrupted after $tdiff seconds ◀\e[0m"
    kill $PPID
    exit 1
}
trap 'int_handler' INT

TRIES=16

if [ $# -ne 1 ]; then
    echo "Usage: `basename $0` <url-or-id>"
    exit 1
fi

n=0
success=false
while [ "$n" -lt "$TRIES" ]; do
    let "n+=1"

    echo -e "\e[36m──────────────────────────── Try #$n ────────────────────────────\e[0m"

    youtube-dl -- $1
    if [ "$?" -eq 0 ]; then
        success=true
        break
    fi
done

set_tdiff

if [ "$success" = false ]; then
    echo -e "\e[91m✘ Still failed after $TRIES tries in $tdiff seconds; quitting ✘\e[0m"
else
    tries="tries"
    if [ "$n" -eq 1 ]; then
        tries="try"
    fi

    echo -e "\e[92m✔ Success!  (Took $n $tries in $tdiff seconds).\e[0m"
fi
